### PR TITLE
Fix small dimension specification issue.

### LINKED ISSUE #355: Fix: `clplatea` small dimension issue
Currently, ` prob = ADNLPProblems.clplatea(n=N)` fails for all $N < 9$ as a result of this sum in it's definition:

```julia
           sum(
             sum(
               1 // 2 * (x[i + (j - 1) * p] - x[i - 1 + (j - 1) * p])^2 +
               hp2 * (x[i + (j - 1) * p] - x[i - 1 + (j - 1) * p])^4 for j = 2:p
             ) for i = 3:p
           )
```

Where $p$ is defined to be $p = floor(Int, sqrt(n))$. So, $N$ must be greater than  $8$ for `sum( .... for i=3:p)` to be over a non-empty collection.

Suggested fixes:
- Update the warning statement and properly adjust the number of variables to be 9 or greater.
- Or, depending on the province and if it makes sense, we may modify the above sum as `sum((... for i = 3:p); init=0.0)`; but then an issue would arise for $N < 4$ if similar action isn't taken to modify the two other sums in `clplatea`'s definition.

### PR DESCRIPTION
**Pull request by danphenderson**
Resolves #355; tests are passing locally.

### CODE REVIEW

**Review by tmigot — APPROVED** [review]
Thanks @danphenderson !

File: src/ADNLPProblems/clplatea.jl [hunk 1]
```diff
@@ -6,8 +6,8 @@ function clplatea(;
   wght = -0.1,
   kwargs...,
 ) where {T}
-  p = floor(Int, sqrt(n))
-  p * p != n && @warn("clplatea: number of variables adjusted from $n down to $(p*p)")
+  p = floor(Int, sqrt(n)) < 3 ? 3 : floor(Int, sqrt(n))
```
Comment (tmigot) [inline src/ADNLPProblems/clplatea.jl:9]:
```suggestion
  p = max(floor(Int, sqrt(n)), 3)
```

File: src/ADNLPProblems/clplateb.jl [hunk 2]
```diff
@@ -6,8 +6,8 @@ function clplateb(;
   wght = -0.1,
   kwargs...,
 ) where {T}
-  p = floor(Int, sqrt(n))
-  p * p != n && @warn("clplateb: number of variables adjusted from $n down to $(p*p)")
+  p = floor(Int, sqrt(n)) < 3 ? 3 : floor(Int, sqrt(n))
```
Comment (tmigot) [inline src/ADNLPProblems/clplateb.jl:9]:
```suggestion
  p = max(floor(Int, sqrt(n)), 3)
```

File: src/ADNLPProblems/clplatec.jl [hunk 3]
```diff
@@ -8,8 +8,8 @@ function clplatec(;
   l = 0.01,
   kwargs...,
 ) where {T}
-  p = floor(Int, sqrt(n))
-  p * p != n && @warn("clplatec: number of variables adjusted from $n down to $(p*p)")
+  p = floor(Int, sqrt(n)) < 3 ? 3 : floor(Int, sqrt(n))
```
Comment (tmigot) [inline src/ADNLPProblems/clplatec.jl:11]:
```suggestion
  p = max(floor(Int, sqrt(n)), 3)
```

**Review by tmigot — CHANGES_REQUESTED** [review]
